spring:
  application:
    name: bcapi
  mvc:
    problemdetails:
      enabled: true
  liquibase:
    contexts: default

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
